# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-12 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classfication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Direaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('classfication', models.ManyToManyField(to='UnionSearchApp.Classfication', verbose_name='分类')),
            ],
            options={
                'verbose_name': '方向',
                'verbose_name_plural': '方向',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
            ],
            options={
                'verbose_name': '级别',
                'verbose_name_plural': '级别',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='状态')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('desc', models.CharField(max_length=128, verbose_name='简介')),
                ('weight', models.IntegerField(default=0, help_text='权重按照从大到小排列', verbose_name='权重（从大到小排列）')),
                ('img', models.ImageField(blank=True, null=True, upload_to='./static/img/', verbose_name='图片')),
                ('href', models.URLField(verbose_name='视频地址')),
                ('classfication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UnionSearchApp.Classfication', verbose_name='分类')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UnionSearchApp.Level', verbose_name='级别')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
    ]
