# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-12 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UnionSearchApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='direaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UnionSearchApp.Direaction', verbose_name='方向'),
        ),
    ]
